/*
 * Generated by Digiblock. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module PriorityEncoder5 (
    input in0,
    input in1,
    input in2,
    input in3,
    input in4,
    input in5,
    input in6,
    input in7,
    input in8,
    input in9,
    input in10,
    input in11,
    input in12,
    input in13,
    input in14,
    input in15,
    input in16,
    input in17,
    input in18,
    input in19,
    input in20,
    input in21,
    input in22,
    input in23,
    input in24,
    input in25,
    input in26,
    input in27,
    input in28,
    input in29,
    input in30,
    input in31,
    output reg [4:0] num,
    output any
);
    always @ (*) begin
        if (in31 == 1'b1)
            num = 5'h1f;
        else if (in30 == 1'b1)
            num = 5'h1e;
        else if (in29 == 1'b1)
            num = 5'h1d;
        else if (in28 == 1'b1)
            num = 5'h1c;
        else if (in27 == 1'b1)
            num = 5'h1b;
        else if (in26 == 1'b1)
            num = 5'h1a;
        else if (in25 == 1'b1)
            num = 5'h19;
        else if (in24 == 1'b1)
            num = 5'h18;
        else if (in23 == 1'b1)
            num = 5'h17;
        else if (in22 == 1'b1)
            num = 5'h16;
        else if (in21 == 1'b1)
            num = 5'h15;
        else if (in20 == 1'b1)
            num = 5'h14;
        else if (in19 == 1'b1)
            num = 5'h13;
        else if (in18 == 1'b1)
            num = 5'h12;
        else if (in17 == 1'b1)
            num = 5'h11;
        else if (in16 == 1'b1)
            num = 5'h10;
        else if (in15 == 1'b1)
            num = 5'hf;
        else if (in14 == 1'b1)
            num = 5'he;
        else if (in13 == 1'b1)
            num = 5'hd;
        else if (in12 == 1'b1)
            num = 5'hc;
        else if (in11 == 1'b1)
            num = 5'hb;
        else if (in10 == 1'b1)
            num = 5'ha;
        else if (in9 == 1'b1)
            num = 5'h9;
        else if (in8 == 1'b1)
            num = 5'h8;
        else if (in7 == 1'b1)
            num = 5'h7;
        else if (in6 == 1'b1)
            num = 5'h6;
        else if (in5 == 1'b1)
            num = 5'h5;
        else if (in4 == 1'b1)
            num = 5'h4;
        else if (in3 == 1'b1)
            num = 5'h3;
        else if (in2 == 1'b1)
            num = 5'h2;
        else if (in1 == 1'b1)
            num = 5'h1;
        else 
            num = 5'h0;
    end

    assign any = in0 | in1 | in2 | in3 | in4 | in5 | in6 | in7 | in8 | in9 | in10 | in11 | in12 | in13 | in14 | in15 | in16 | in17 | in18 | in19 | in20 | in21 | in22 | in23 | in24 | in25 | in26 | in27 | in28 | in29 | in30 | in31;
endmodule

module \0 check  (
  input [31:0] in,
  output [4:0] out,
  output zero
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  assign s0 = in[0];
  assign s1 = in[1];
  assign s2 = in[2];
  assign s3 = in[3];
  assign s4 = in[4];
  assign s5 = in[5];
  assign s6 = in[6];
  assign s7 = in[7];
  assign s8 = in[8];
  assign s9 = in[9];
  assign s10 = in[10];
  assign s11 = in[11];
  assign s12 = in[12];
  assign s13 = in[13];
  assign s14 = in[14];
  assign s15 = in[15];
  assign s16 = in[16];
  assign s17 = in[17];
  assign s18 = in[18];
  assign s19 = in[19];
  assign s20 = in[20];
  assign s21 = in[21];
  assign s22 = in[22];
  assign s23 = in[23];
  assign s24 = in[24];
  assign s25 = in[25];
  assign s26 = in[26];
  assign s27 = in[27];
  assign s28 = in[28];
  assign s29 = in[29];
  assign s30 = in[30];
  assign s31 = in[31];
  PriorityEncoder5 PriorityEncoder5_i0 (
    .in0( s0 ),
    .in1( s1 ),
    .in2( s2 ),
    .in3( s3 ),
    .in4( s4 ),
    .in5( s5 ),
    .in6( s6 ),
    .in7( s7 ),
    .in8( s8 ),
    .in9( s9 ),
    .in10( s10 ),
    .in11( s11 ),
    .in12( s12 ),
    .in13( s13 ),
    .in14( s14 ),
    .in15( s15 ),
    .in16( s16 ),
    .in17( s17 ),
    .in18( s18 ),
    .in19( s19 ),
    .in20( s20 ),
    .in21( s21 ),
    .in22( s22 ),
    .in23( s23 ),
    .in24( s24 ),
    .in25( s25 ),
    .in26( s26 ),
    .in27( s27 ),
    .in28( s28 ),
    .in29( s29 ),
    .in30( s30 ),
    .in31( s31 ),
    .num( out ),
    .any( zero )
  );
endmodule
