/*
 * Generated by Digiblock. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module \absolute-final-inc  (
  input EN,
  input [1:0] P,
  output [1:0] Q,
  output OT
);
  wire const1b0;
  wire s0;
  wire OT_temp;
  assign const1b0 = 1'b0;
  assign s0 = P[0];
  assign OT_temp = (s0 | const1b0);
  assign Q[0] = ((EN & const1b0) ^ s0);
  assign Q[1] = ((EN & OT_temp) ^ P[1]);
  assign OT = OT_temp;
endmodule
