/*
 * Generated by Digiblock. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module adder (
  input A, // first bit to add
  input B, // second bit to add
  input \C_{i-1} , // carry in
  output C_i, // carry bit
  output S // sum

);
  wire s0;
  assign s0 = (A ^ B);
  assign S = (s0 ^ \C_{i-1} );
  assign C_i = ((A & B) | (s0 & \C_{i-1} ));
endmodule
